version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Password123"  # Set a strong password
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"  # Can be set to Developer, Express, or any other edition
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql  # Persistent data storage

volumes:
  mssql-data:
    driver: local

